[package]
edition = "2021"
name = "spotify"
version = "0.1.0"

[dependencies]
librespot = {git = "https://github.com/oeed/librespot", branch = "spirc-load-command"}
serde = "1"
serde_json = "1"
swift-bridge = {version = "0.1", features = ["async"]}
tokio = "1"
